name: Zoo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.11.4=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - cachetools==5.5.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - networkx==3.1
      - numpy==1.24.3
      - oauthlib==3.3.1
      - packaging==25.0
      - pillow==10.4.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.21.0
      - scipy==1.10.1
      - six==1.17.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tifffile==2023.7.10
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /home/yfandeng/scratch/.conda/envs/BadPart
